75_problems:
  problem_type:
    - Array / String
    - Two Pointers
    - Sliding Window
    - Prefix Sum
    - Hash Map / Set
    - Stack
    - Queue
    - Linked List
    - Binary Tree - DFS
    - Binary Tree - BFS
    - Graphs - DFS
    - Graphs - BFS
    - Heap / Priority Queue
    - Binary Search
    - Backtracking
    - DP - 1D
    - DP - Multidimensional
    - Bit Manipulation
    - Trie
    - Intervals
    - Monotonic Stack
learning_path:
  problem_type:
    - DP
    - GRAPH
    - HEAP
    - BIT Manipulation
    - SORTING
    - Google
    - Facebook
    - Amazon
    - Apple
    - Microsoft
    - SQL